version: '3'
services:
  mongodb:
    image: mongo:5
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      MONGO_INITDB_DATABASE: reddit
    networks:
      - node-network
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://mongodb:27017/reddit
    networks:
      - node-network
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      API_URI: http://server:8080/api
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
